### ISSUE TITLE
Icons not changing 1.15.2

### ISSUE THREAD

**Issue by PanoptesDreams** [Szum123321/window_title_changer#1]
In the config I have tried setting the:
"icon16x16": ""
"icon32x32": ""
 to various things and none of them work.

E.G:
"icon16x16": "16x16",
"icon32x32": "32x32"
-or-
"icon16x16": "16x16.ico",
"icon32x32": "32x32.ico"

**Comment by PanoptesDreams** [comment]
I have gone through the source and found my answer.
However this did not help either. Following what the code said, I did and the icons still don't change.

So there must be a bug in changing the icons.

**Comment by Szum123321** [comment]
Inside config folder of this mod, there is another folder called icons. You have to put both files there and then just set "icon16x16" and "icon32x32" to their name. For example: let's say my 16 by 16 pixels icon is called "superIconSmall.png" and 32 by 32 "superIconBig.png". Than config file should look like this: "icon16x16": "superIconSmall.png", "icon32x32": "superIconBig.png".

**Comment by PanoptesDreams** [comment]
oh, so they pngs? not icos?
That would help to clarify

**Comment by PanoptesDreams** [comment]
Please update your documentation to reflect this. What seems obvious to you may not to others.

**Comment by Szum123321** [comment]
But does it work now?

**Comment by PanoptesDreams** [comment]
It does, thank you.
